name: 'Test'

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        node: [12.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v1
    - name: 'Use Node.js ${{ inputs.node_version }}'
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}
    - name: 'Install yarn'
    - run: npm install -g yarn
    - name: 'Yarn: install, build, and test'
      run: |
        yarn
        yarn build
        yarn test
      env:
        CI: true
