name: Node CI

on: [pull_request]

jobs:
  build:

    strategy:
      matrix:
        node: [10.x]
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: Dm1Korneev/install-build-test-action@master
