name: Node CI

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: Dm1Korneev/install-build-test-action
      with:
        node_version: ${{ matrix.node-version }}
